# Generated by Django 3.0.7 on 2020-06-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiredapp', '0004_employeeprofile_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='pay',
            field=models.CharField(default='$7.25/hr', max_length=20),
        ),
    ]
