# Generated by Django 3.0.7 on 2020-06-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiredapp', '0005_auto_20200619_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(default='https://pecb.com/conferences/wp-content/uploads/2017/10/no-profile-picture.jpg', upload_to=''),
        ),
    ]
